#!/bin/bash
if [[ $1 = 'send' ]]; then
  rsync -va data/ benedict:~/app-root/data/
else
  rsync -va benedict:~/app-root/data/uploads data/
  ssh benedict 'mysqldump -h $OPENSHIFT_MYSQL_DB_HOST -P ${OPENSHIFT_MYSQL_DB_PORT:-3306} -u ${OPENSHIFT_MYSQL_DB_USERNAME:-"admin"} --password="$OPENSHIFT_MYSQL_DB_PASSWORD" --all-databases > ~/app-root/data/dump.sql'
  scp benedict:~/app-root/data/dump.sql data/
fi

